// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOuFx11T_QwhFbuHHt-ofCSTOLUXLNRE',
    appId: '1:898928361646:web:bf53e0d5042371c39dad3f',
    messagingSenderId: '898928361646',
    projectId: 'todo-889db',
    authDomain: 'todo-889db.firebaseapp.com',
    storageBucket: 'todo-889db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI8Td1gmtKUcCbAPDL125_M8sahGYfJA8',
    appId: '1:898928361646:android:ba9f80487fd69f019dad3f',
    messagingSenderId: '898928361646',
    projectId: 'todo-889db',
    storageBucket: 'todo-889db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_SFWLv8cK6E0G6QoA1eYq4YJ4RAj5w0',
    appId: '1:898928361646:ios:9c40b536b4f126ca9dad3f',
    messagingSenderId: '898928361646',
    projectId: 'todo-889db',
    storageBucket: 'todo-889db.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy_SFWLv8cK6E0G6QoA1eYq4YJ4RAj5w0',
    appId: '1:898928361646:ios:9c40b536b4f126ca9dad3f',
    messagingSenderId: '898928361646',
    projectId: 'todo-889db',
    storageBucket: 'todo-889db.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOuFx11T_QwhFbuHHt-ofCSTOLUXLNRE',
    appId: '1:898928361646:web:6b8ff56ba215b7619dad3f',
    messagingSenderId: '898928361646',
    projectId: 'todo-889db',
    authDomain: 'todo-889db.firebaseapp.com',
    storageBucket: 'todo-889db.appspot.com',
  );
}
